name: lightgan-ld
channels: [pytorch, nvidia, conda-forge, defaults]
dependencies:
  - python=3.10
  - pytorch>=2.4
  - torchvision>=0.19
  - pytorch-cuda=12.1
  - pip
  - pip:
      - numpy>=1.26
      - scipy>=1.11
      - tqdm>=4.66
      - pillow>=10.0
      - opencv-python>=4.8
      - pyyaml>=6.0.1
      - einops>=0.8.0
      - lpips>=0.1.4
      - ptflops>=0.7.3
      - thop>=0.1.1-post2209072238
      - tensorboard>=2.17.0
      - pre-commit
      - pytest
      - h5py
